apiVersion: v1
kind: Service
metadata:
  name: dvga-service
spec:
  selector:
    app: dvga
  ports:
    - protocol: TCP
      port: 5013
      targetPort: 5013  # Match the container port
  type: NodePort