apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dvga-service-monitor
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - default  
  selector:
    matchLabels:
      app: dvga
  endpoints:
    - port: "http"  
      interval: 15s
