apiVersion: v1
kind: Service
metadata:
  name: dvga-service
  namespace: monitoring
  labels:
    app: dvga  
spec:
  selector:
    app: dvga
  ports:
    - name: http  
      port: 5013
      targetPort: 5013
