apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dvga-service-monitor
  namespace: prometheus
  labels:
    prometheus: kube-prometheus  
spec:
  selector:
    matchLabels:
      app: dvga
  endpoints:
    - port: "5013"
      interval: 15s
