apiVersion: v1
kind: Service
metadata:
  name: projet-log-8100-lb-grafana
  namespace: prometheus
spec:
  selector: 
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer