- name: Deploy application to AKS cluster
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_image_name: "{{ lookup('env', 'DOCKER_IMAGE_NAME') }}"
    discord_webhook_url: " ${{ secrets.DISCORD_WEBHOOK_URL }}"
    
  tasks:
    - name: Ensure the default namespace exists
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: default

    - name: Add Prometheus Helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Install kube-prometheus-stack
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: prometheus
        create_namespace: true
        values:
          prometheus:
            service:
              type: LoadBalancer
          grafana:
            service:
              type: LoadBalancer


    - name: Create deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: dvga
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: dvga
            template:
              metadata:
                labels:
                  app: dvga
              spec:
                containers:
                  - name: dvga-container
                    image: "{{ docker_image_name }}:latest"
                    ports:
                      - containerPort: 5013

    - name: Create Service for dvga
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: dvga-service
            namespace: default
            labels:
              app: dvga
          spec:
            selector:
              app: dvga
            ports:
              - name: http
                port: 5013
                targetPort: 5013

    - name: Deploy ServiceMonitor for dvga
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition: "{{ lookup('file', 'dvga-servicemonitor.yaml') }}"

    - name: Create ConfigMap for Prometheus
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: prometheus-config
            namespace: prometheus
          data:
            prometheus.yml: |
              global:
                scrape_interval: 15s
              scrape_configs:
                - job_name: 'prometheus'
                  static_configs:
                    - targets: ['localhost:9090']
                - job_name: 'dvga-metrics'
                  metrics_path: '/metrics'
                  static_configs:
                    - targets: ['dvga-service.default.svc.cluster.local:5013']
                    
    - name: Restart Prometheus StatefulSet to apply ConfigMap
      command: >
        kubectl rollout restart statefulset prometheus-prometheus-kube-prometheus-prometheus -n prometheus

    - name: Vérifier les vulnérabilités critiques dans Prometheus
      command: |
        curl -s http://prometheus-prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090/api/v1/query \
        --data-urlencode 'query=ALERTS{alertstate="firing"}'
      register: prometheus_alerts


    - name: Envoyer les alertes critiques à Discord
      when: prometheus_alerts.stdout.find('severity="critical"') != -1
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: |
            🚨 **Alerte Critique Détectée !**
            Détails : {{ prometheus_alerts.stdout }}

    - name: Envoyer les alertes warning à Discord
      when: prometheus_alerts.stdout.find('severity="warning"') != -1
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: |
            ⚠️ **Alerte Warning Détectée !**
            Détails : {{ prometheus_alerts.stdout }}


    - name: Envoyer les alertes info à Discord
      when: prometheus_alerts.stdout.find('severity="info"') != -1
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: |
            ℹ️ **Alerte Informationnelle Détectée !**
            Détails : {{ prometheus_alerts.stdout }}

