name: Build and Deploy to AKS

on:
  push:
    branches:
      - ci-test

jobs:
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2  

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_IMAGE_NAME }}:latest" .

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

  trivy_scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

      - name: Run Trivy - Generate report
        run: |
          docker run --rm -v ${{ github.workspace }}/.trivycache:/root/.cache/ \
            -v ${{ github.workspace }}:/workspace aquasec/trivy image --exit-code 0 \
            --format json --output "/workspace/trivy-report.json" "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.json

  clair_scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Clair network
        run: docker network create clair_network

      - name: Run Clair service
        run: |
          docker run -d --name clair --network clair_network -p 6060:6060 \
          -v ${{ github.workspace }}/config.yaml:/etc/clair/config.yaml \
          quay.io/projectquay/clair:4.7.2 clair -config /etc/clair/config.yaml

      - name: Wait for Clair to start
        run: |
          for i in {1..30}; do
            curl --silent http://localhost:6060/v1/indexer/api/v1/index_report && break
            echo "Waiting for Clair to initialize..."
            sleep 5
          done

      - name: Analyze Docker image with Clair
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"image":"docker://${{ secrets.DOCKER_IMAGE_NAME }}:latest"}' \
            http://localhost:6060/v1/indexer/api/v1/index_report

      - name: Fetch Clair report
        run: |
          curl -X GET http://localhost:6060/v1/indexer/api/v1/index_report \
            -o clair-report.json

      - name: Upload Clair report
        uses: actions/upload-artifact@v3
        with:
          name: clair-report
          path: clair-report.json

