name: Build and Deploy to AKS

on:
  push:
    branches:
      - ci-test

jobs:
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2  

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_IMAGE_NAME }}:latest" .

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

  trivy_scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

      - name: Run Trivy - Generate report
        run: |
          docker run --rm -v ${{ github.workspace }}/.trivycache:/root/.cache/ \
            -v ${{ github.workspace }}:/workspace aquasec/trivy image --exit-code 0 \
            --format json --output "/workspace/trivy-report.json" "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.json

  clair_scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run clair db
        run: docker run -d --name clair-db arminc/clair-db:latest

      - name: Run Clair service
        run: |
          docker run -p 6060:6060 --link clair-db:postgres -d --name clair arminc/clair-local-scan:latest

      - name: Wait for Clair to start
        run: sleep 15

      - name: Install Clair scanner
        run: |
          curl -L https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 \
          -o /usr/bin/clair-scanner
          chmod +x /usr/bin/clair-scanner

      - name: Analyze Docker image with Clair
        env:
          CLAIR_ADDR: http://localhost:6060
        run: |
          clair-scanner -r clair-report.json \
          --ip "$(hostname -I | awk '{print $1}')" "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

      - name: Upload Clair report
        uses: actions/upload-artifact@v3
        with:
          name: clair-report
          path: clair-report.json

