name: Build and Deploy to AKS

on:
  push:
    branches:
      - ci-test

jobs:
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2  

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_IMAGE_NAME }}:latest" .
      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

  trivy_scan:
    needs: build-and-push 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

      - name: Create workspace directory
        run: mkdir -p ${{ github.workspace }}/workspace

      - name: Run Trivy - Clear cache
        run: docker run --rm -v ${{ github.workspace }}/.trivycache:/root/.cache/ aquasec/trivy clean --scan-cache

      - name: Run Trivy - Download DB
        run: docker run --rm -v ${{ github.workspace }}/.trivycache:/root/.cache/ aquasec/trivy image --download-db-only

      - name: Run Trivy - Generate report
        run: docker run --rm -v ${{ github.workspace }}/.trivycache:/root/.cache/ -v ${{ github.workspace }}:/workspace aquasec/trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl" --output "/workspace/trivy-report.json" "${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}"

      - name: Run Trivy - Critical severity
        run: docker run --rm -v ${{ github.workspace }}/.trivycache:/root/.cache/ aquasec/trivy image --exit-code 1 --severity CRITICAL "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.json

  clair_scan:
    needs: trivy_scan 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull "${{ secrets.DOCKER_IMAGE_NAME }}:latest"

      - name: Run Clair combo mode
        run: |
          docker run -d --rm --name clair -p 6060:6060 -p 6061:6061 quay.io/projectquay/clair:4.7.2 clair -mode combo
          sleep 10 # Allow Clair to start

      - name: Generate Clair report
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace quay.io/projectquay/clairctl:latest clairctl report "${{ secrets.DOCKER_IMAGE_NAME }}:latest" --format json > /workspace/clair-report.json

      - name: Upload Clair report
        uses: actions/upload-artifact@v3
        with:
          name: clair-report
          path: clair-report.json
