name: CI/CD-pipeline-project

on:
  push:
    branches:
      - ci-test
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarqube:
    name: Sonarqube-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analyze code
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  security:
    name: Snyk-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@v0.6.0
        with:
          args: test --file=requirements.txt --package-manager=pip
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Verify Snyk CLI
        run: snyk --version
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
